version: '3.3'

services:
  redis:
    image: redis:5-alpine
    expose:
      - "6379"
  db:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=megasecretpassword
      - POSTGRES_DB=db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p 5432
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - redis
      - db

volumes:
  postgres-data: